FROM node:20.18-alpine AS base

RUN npm i -g pnpm

FROM base AS server-dependencies

WORKDIR /usr/src/app/server

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

FROM base AS server-build

WORKDIR /usr/src/app/server

COPY . .

COPY --from=server-dependencies /usr/src/app/server/node_modules ./node_modules

RUN pnpm build

RUN pnpm prune --prod

FROM node:20.18-alpine AS production

WORKDIR /usr/src/app

COPY --from=server-build --chown=nodejs:nodejs /usr/src/app/server/dist ./dist
COPY --from=server-build --chown=nodejs:nodejs /usr/src/app/server/node_modules ./node_modules
COPY --from=server-build --chown=nodejs:nodejs /usr/src/app/server/package.json ./package.json

USER 1000

EXPOSE 3000

CMD ["node", "dist/server.js"]
