services:

  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=$DATABASE_URL
      - PORT=3000
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - pg
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    volumes:
      - './docker:/docker-entrypoint-initdb.d'
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: